# Generated by Django 5.2.7 on 2025-10-17 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
                'db_table': 'customer_info',
            },
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.CharField(max_length=10, verbose_name='楼栋号')),
                ('unit_number', models.CharField(max_length=10, verbose_name='单元号')),
                ('room_number', models.CharField(max_length=10, verbose_name='房间号')),
                ('floor_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='建筑面积')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment_app.customerinfo', verbose_name='客户信息')),
            ],
            options={
                'verbose_name': '房间信息',
                'verbose_name_plural': '房间信息',
                'db_table': 'room_info',
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_year', models.IntegerField(verbose_name='缴费年份')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='缴费金额')),
                ('payment_order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='支付单号')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_app.roominfo', verbose_name='房间信息')),
            ],
            options={
                'verbose_name': '缴费信息',
                'verbose_name_plural': '缴费信息',
                'db_table': 'payment_info',
            },
        ),
        migrations.AddIndex(
            model_name='roominfo',
            index=models.Index(fields=['building_number', 'unit_number', 'room_number'], name='room_info_buildin_8ef70a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roominfo',
            unique_together={('building_number', 'unit_number', 'room_number')},
        ),
        migrations.AddIndex(
            model_name='paymentinfo',
            index=models.Index(fields=['room'], name='payment_inf_room_id_418a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinfo',
            index=models.Index(fields=['payment_year'], name='payment_inf_payment_52afeb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinfo',
            index=models.Index(fields=['payment_time'], name='payment_inf_payment_43a230_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentinfo',
            unique_together={('room', 'payment_year')},
        ),
    ]
